
title: cat llorllale | grep -v 'BS'
name: George Aristy
author: George Aristy
email: george.aristy@gmail.com
timezone: America/Santo_Domingo
locale: en-US
description: > # this means to ignore newlines until "baseurl:"
  Ops support, programmer, budding enterprise architect, powerlifter, guitar player (maybe).
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  llorllale
linkedin_username: georgearisty
repository: llorllale/llorllale.github.io

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
